// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MembershipRole string

const (
	MembershipRoleMember     MembershipRole = "Member"
	MembershipRoleSubscriber MembershipRole = "Subscriber"
	MembershipRoleAdmin      MembershipRole = "Admin"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type Comment struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	PublisherID     pgtype.UUID        `json:"publisher_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	CommentBody     string             `json:"comment_body"`
	NumRays         int32              `json:"num_rays"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Follow struct {
	ID          pgtype.UUID        `json:"id"`
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID          pgtype.UUID        `json:"id"`
	PublisherID pgtype.UUID        `json:"publisher_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	PostContent []byte             `json:"post_content"`
	NumRays     int32              `json:"num_rays"`
	NumComments int32              `json:"num_comments"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PostImage struct {
	ID               pgtype.UUID        `json:"id"`
	PostID           pgtype.UUID        `json:"post_id"`
	ImageUrl         string             `json:"image_url"`
	ImageDescription string             `json:"image_description"`
	AltText          *string            `json:"alt_text"`
	IsCoverImage     bool               `json:"is_cover_image"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PostVideo struct {
	ID             pgtype.UUID        `json:"id"`
	PostID         pgtype.UUID        `json:"post_id"`
	YoutubeVideoID string             `json:"youtube_video_id"`
	VideoMetadata  []byte             `json:"video_metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Username        string             `json:"username"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	ProfileBio      []byte             `json:"profile_bio"`
	NumRaysReceived int32              `json:"num_rays_received"`
	Role            MembershipRole     `json:"role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Ray struct {
	ID          pgtype.UUID        `json:"id"`
	PublisherID pgtype.UUID        `json:"publisher_id"`
	PostID      pgtype.UUID        `json:"post_id"`
	CommentID   pgtype.UUID        `json:"comment_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SavedPost struct {
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
