// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppRole string

const (
	AppRoleUser  AppRole = "User"
	AppRoleAdmin AppRole = "Admin"
)

func (e *AppRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppRole(s)
	case string:
		*e = AppRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppRole: %T", src)
	}
	return nil
}

type NullAppRole struct {
	AppRole AppRole `json:"app_role"`
	Valid   bool    `json:"valid"` // Valid is true if AppRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppRole), nil
}

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus `json:"post_status"`
	Valid      bool       `json:"valid"` // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type SubscriberTier string

const (
	SubscriberTierMember     SubscriberTier = "Member"
	SubscriberTierSubscriber SubscriberTier = "Subscriber"
)

func (e *SubscriberTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriberTier(s)
	case string:
		*e = SubscriberTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriberTier: %T", src)
	}
	return nil
}

type NullSubscriberTier struct {
	SubscriberTier SubscriberTier `json:"subscriber_tier"`
	Valid          bool           `json:"valid"` // Valid is true if SubscriberTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriberTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriberTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriberTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriberTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriberTier), nil
}

type Comment struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	PublisherID     pgtype.UUID        `json:"publisher_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	CommentBody     string             `json:"comment_body"`
	NumRays         int32              `json:"num_rays"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Follow struct {
	ID          pgtype.UUID        `json:"id"`
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID          pgtype.UUID        `json:"id"`
	PublisherID pgtype.UUID        `json:"publisher_id"`
	Title       string             `json:"title"`
	Subtitle    *string            `json:"subtitle"`
	Slug        string             `json:"slug"`
	PostContent []byte             `json:"post_content"`
	NumRays     int32              `json:"num_rays"`
	NumComments int32              `json:"num_comments"`
	Status      PostStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PostImage struct {
	ID               pgtype.UUID        `json:"id"`
	PostID           pgtype.UUID        `json:"post_id"`
	ImageUrl         string             `json:"image_url"`
	ImageDescription *string            `json:"image_description"`
	AltText          *string            `json:"alt_text"`
	IsCoverImage     bool               `json:"is_cover_image"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type PostVideo struct {
	ID             pgtype.UUID        `json:"id"`
	PostID         pgtype.UUID        `json:"post_id"`
	YoutubeVideoID string             `json:"youtube_video_id"`
	VideoMetadata  []byte             `json:"video_metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Username        string             `json:"username"`
	ProfileImageUrl *string            `json:"profile_image_url"`
	ProfileBio      *string            `json:"profile_bio"`
	NumRaysReceived int32              `json:"num_rays_received"`
	SubscriberTier  SubscriberTier     `json:"subscriber_tier"`
	AppRole         AppRole            `json:"app_role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Ray struct {
	ID          pgtype.UUID        `json:"id"`
	PublisherID pgtype.UUID        `json:"publisher_id"`
	PostID      pgtype.UUID        `json:"post_id"`
	CommentID   pgtype.UUID        `json:"comment_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SavedPost struct {
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
