// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM posts WHERE slug = $1
)
`

func (q *Queries) CheckSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSlugExistsOtherPosts = `-- name: CheckSlugExistsOtherPosts :one
SELECT EXISTS(
    SELECT 1 FROM posts WHERE slug = $1 and id != $2
)
`

type CheckSlugExistsOtherPostsParams struct {
	Slug string      `json:"slug"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) CheckSlugExistsOtherPosts(ctx context.Context, arg CheckSlugExistsOtherPostsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlugExistsOtherPosts, arg.Slug, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countPostsByUserToday = `-- name: CountPostsByUserToday :one
SELECT COUNT(*) FROM posts
WHERE publisher_id = $1 
AND created_at >= CURRENT_DATE
AND deleted_at IS NULL
`

func (q *Queries) CountPostsByUserToday(ctx context.Context, publisherID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByUserToday, publisherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    publisher_id, title, subtitle, slug, post_content, status, num_rays, num_comments
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, publisher_id, title, subtitle, slug, post_content, num_rays, num_comments, status, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	PublisherID pgtype.UUID `json:"publisher_id"`
	Title       string      `json:"title"`
	Subtitle    *string     `json:"subtitle"`
	Slug        string      `json:"slug"`
	PostContent []byte      `json:"post_content"`
	Status      PostStatus  `json:"status"`
	NumRays     int32       `json:"num_rays"`
	NumComments int32       `json:"num_comments"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.PublisherID,
		arg.Title,
		arg.Subtitle,
		arg.Slug,
		arg.PostContent,
		arg.Status,
		arg.NumRays,
		arg.NumComments,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Subtitle,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT 
    p.id,
    p.publisher_id, 
    p.title,
    p.subtitle,
    p.slug,
    p.post_content,
    p.status,       
    p.num_rays,
    p.num_comments,
    p.created_at,
    pi.image_url AS cover_image_url,
    pi.alt_text AS cover_image_alt,
    pr.username AS publisher_username,
    pr.profile_image_url AS publisher_avatar
FROM posts p
LEFT JOIN post_images pi ON p.id = pi.post_id AND pi.is_cover_image = true
LEFT JOIN profiles pr ON p.publisher_id = pr.id
WHERE p.deleted_at IS NULL AND p.status = 'published'
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPostsRow struct {
	ID                pgtype.UUID        `json:"id"`
	PublisherID       pgtype.UUID        `json:"publisher_id"`
	Title             string             `json:"title"`
	Subtitle          *string            `json:"subtitle"`
	Slug              string             `json:"slug"`
	PostContent       []byte             `json:"post_content"`
	Status            PostStatus         `json:"status"`
	NumRays           int32              `json:"num_rays"`
	NumComments       int32              `json:"num_comments"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CoverImageUrl     *string            `json:"cover_image_url"`
	CoverImageAlt     *string            `json:"cover_image_alt"`
	PublisherUsername *string            `json:"publisher_username"`
	PublisherAvatar   *string            `json:"publisher_avatar"`
}

// ONLY SHOW PUBLISHED POSTS in the main feed
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublisherID,
			&i.Title,
			&i.Subtitle,
			&i.Slug,
			&i.PostContent,
			&i.Status,
			&i.NumRays,
			&i.NumComments,
			&i.CreatedAt,
			&i.CoverImageUrl,
			&i.CoverImageAlt,
			&i.PublisherUsername,
			&i.PublisherAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentlyDeletePost = `-- name: PermanentlyDeletePost :one
DELETE FROM posts
WHERE id = $1 AND publisher_id = $2
RETURNING id, publisher_id, title, subtitle, slug, post_content, num_rays, num_comments, status, created_at, updated_at, deleted_at
`

type PermanentlyDeletePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
}

func (q *Queries) PermanentlyDeletePost(ctx context.Context, arg PermanentlyDeletePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, permanentlyDeletePost, arg.ID, arg.PublisherID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Subtitle,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectPostByID = `-- name: SelectPostByID :one
SELECT 
    p.id, p.publisher_id, p.title, p.subtitle, p.slug, p.post_content, p.num_rays, p.num_comments, p.status, p.created_at, p.updated_at, p.deleted_at,
    -- Publisher Data (Added First/Last Name)
    pr.first_name AS publisher_first_name,
    pr.last_name AS publisher_last_name,
    pr.username AS publisher_username,
    pr.profile_image_url AS publisher_avatar,
    pr.subscriber_tier AS publisher_role,
    -- Image Data
    pi.id AS image_id,
    pi.image_url AS cover_image_url,
    pi.alt_text AS cover_image_alt,
    -- Video Data 
    pv.id AS video_id,
    pv.youtube_video_id,
    pv.video_metadata
FROM posts p
LEFT JOIN profiles pr ON p.publisher_id = pr.id 
LEFT JOIN post_images pi ON p.id = pi.post_id AND pi.is_cover_image = true
LEFT JOIN post_videos pv ON p.id = pv.post_id
WHERE p.id = $1 AND p.deleted_at IS NULL LIMIT 1
`

type SelectPostByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PublisherID        pgtype.UUID        `json:"publisher_id"`
	Title              string             `json:"title"`
	Subtitle           *string            `json:"subtitle"`
	Slug               string             `json:"slug"`
	PostContent        []byte             `json:"post_content"`
	NumRays            int32              `json:"num_rays"`
	NumComments        int32              `json:"num_comments"`
	Status             PostStatus         `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	PublisherFirstName *string            `json:"publisher_first_name"`
	PublisherLastName  *string            `json:"publisher_last_name"`
	PublisherUsername  *string            `json:"publisher_username"`
	PublisherAvatar    *string            `json:"publisher_avatar"`
	PublisherRole      *SubscriberTier    `json:"publisher_role"`
	ImageID            pgtype.UUID        `json:"image_id"`
	CoverImageUrl      *string            `json:"cover_image_url"`
	CoverImageAlt      *string            `json:"cover_image_alt"`
	VideoID            pgtype.UUID        `json:"video_id"`
	YoutubeVideoID     *string            `json:"youtube_video_id"`
	VideoMetadata      []byte             `json:"video_metadata"`
}

func (q *Queries) SelectPostByID(ctx context.Context, id pgtype.UUID) (SelectPostByIDRow, error) {
	row := q.db.QueryRow(ctx, selectPostByID, id)
	var i SelectPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Subtitle,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PublisherFirstName,
		&i.PublisherLastName,
		&i.PublisherUsername,
		&i.PublisherAvatar,
		&i.PublisherRole,
		&i.ImageID,
		&i.CoverImageUrl,
		&i.CoverImageAlt,
		&i.VideoID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
	)
	return i, err
}

const selectPostBySlug = `-- name: SelectPostBySlug :one
SELECT 
    p.id, p.publisher_id, p.title, p.subtitle, p.slug, p.post_content, p.num_rays, p.num_comments, p.status, p.created_at, p.updated_at, p.deleted_at,
    -- Publisher Data
    pr.first_name AS publisher_first_name,
    pr.last_name AS publisher_last_name,
    pr.username AS publisher_username,
    pr.profile_image_url AS publisher_avatar,
    pr.subscriber_tier AS publisher_role,
    -- Image Data
    pi.id AS image_id,
    pi.image_url AS cover_image_url,
    pi.alt_text AS cover_image_alt,
    -- Video Data
    pv.id AS video_id,
    pv.youtube_video_id,
    pv.video_metadata
FROM posts p
LEFT JOIN profiles pr ON p.publisher_id = pr.id 
LEFT JOIN post_images pi ON p.id = pi.post_id AND pi.is_cover_image = true
LEFT JOIN post_videos pv ON p.id = pv.post_id
WHERE p.slug = $1 AND p.deleted_at IS NULL LIMIT 1
`

type SelectPostBySlugRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PublisherID        pgtype.UUID        `json:"publisher_id"`
	Title              string             `json:"title"`
	Subtitle           *string            `json:"subtitle"`
	Slug               string             `json:"slug"`
	PostContent        []byte             `json:"post_content"`
	NumRays            int32              `json:"num_rays"`
	NumComments        int32              `json:"num_comments"`
	Status             PostStatus         `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	PublisherFirstName *string            `json:"publisher_first_name"`
	PublisherLastName  *string            `json:"publisher_last_name"`
	PublisherUsername  *string            `json:"publisher_username"`
	PublisherAvatar    *string            `json:"publisher_avatar"`
	PublisherRole      *SubscriberTier    `json:"publisher_role"`
	ImageID            pgtype.UUID        `json:"image_id"`
	CoverImageUrl      *string            `json:"cover_image_url"`
	CoverImageAlt      *string            `json:"cover_image_alt"`
	VideoID            pgtype.UUID        `json:"video_id"`
	YoutubeVideoID     *string            `json:"youtube_video_id"`
	VideoMetadata      []byte             `json:"video_metadata"`
}

func (q *Queries) SelectPostBySlug(ctx context.Context, slug string) (SelectPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, selectPostBySlug, slug)
	var i SelectPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Subtitle,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PublisherFirstName,
		&i.PublisherLastName,
		&i.PublisherUsername,
		&i.PublisherAvatar,
		&i.PublisherRole,
		&i.ImageID,
		&i.CoverImageUrl,
		&i.CoverImageAlt,
		&i.VideoID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
	)
	return i, err
}

const selectPostsOfTheDay = `-- name: SelectPostsOfTheDay :many
SELECT 
    p.id,
    p.publisher_id, 
    p.title,
    p.subtitle,
    p.slug,
    p.post_content,
    p.status,       
    p.num_rays,
    p.num_comments,
    p.created_at,
    pi.image_url AS cover_image_url,
    pi.alt_text AS cover_image_alt,
    pr.username AS publisher_username,
    pr.profile_image_url AS publisher_avatar
FROM posts p
LEFT JOIN post_images pi ON p.id = pi.post_id AND pi.is_cover_image = true
LEFT JOIN profiles pr ON p.publisher_id = pr.id
WHERE p.deleted_at IS NULL AND p.status = 'published'
ORDER BY p.num_rays DESC, p.created_at DESC
LIMIT 10
`

type SelectPostsOfTheDayRow struct {
	ID                pgtype.UUID        `json:"id"`
	PublisherID       pgtype.UUID        `json:"publisher_id"`
	Title             string             `json:"title"`
	Subtitle          *string            `json:"subtitle"`
	Slug              string             `json:"slug"`
	PostContent       []byte             `json:"post_content"`
	Status            PostStatus         `json:"status"`
	NumRays           int32              `json:"num_rays"`
	NumComments       int32              `json:"num_comments"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CoverImageUrl     *string            `json:"cover_image_url"`
	CoverImageAlt     *string            `json:"cover_image_alt"`
	PublisherUsername *string            `json:"publisher_username"`
	PublisherAvatar   *string            `json:"publisher_avatar"`
}

// To update later to include videos
// AND p.created_at >= $1
// AND p.created_at < $2
func (q *Queries) SelectPostsOfTheDay(ctx context.Context) ([]SelectPostsOfTheDayRow, error) {
	rows, err := q.db.Query(ctx, selectPostsOfTheDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPostsOfTheDayRow
	for rows.Next() {
		var i SelectPostsOfTheDayRow
		if err := rows.Scan(
			&i.ID,
			&i.PublisherID,
			&i.Title,
			&i.Subtitle,
			&i.Slug,
			&i.PostContent,
			&i.Status,
			&i.NumRays,
			&i.NumComments,
			&i.CreatedAt,
			&i.CoverImageUrl,
			&i.CoverImageAlt,
			&i.PublisherUsername,
			&i.PublisherAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :one
UPDATE posts
SET
    deleted_at = NOW()
WHERE id = $1 AND publisher_id = $2
RETURNING id, publisher_id, title, subtitle, slug, post_content, num_rays, num_comments, status, created_at, updated_at, deleted_at
`

type SoftDeletePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, softDeletePost, arg.ID, arg.PublisherID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Subtitle,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET 
    title = $3,
    subtitle = $4,
    slug = $5,
    post_content = $6,
    status = $7,
    num_rays = $8,
    num_comments = $9,
    updated_at = NOW()
WHERE id = $1 AND publisher_id = $2 AND deleted_at IS NULL 
RETURNING id, publisher_id, title, subtitle, slug, post_content, num_rays, num_comments, status, created_at, updated_at, deleted_at
`

type UpdatePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
	Title       string      `json:"title"`
	Subtitle    *string     `json:"subtitle"`
	Slug        string      `json:"slug"`
	PostContent []byte      `json:"post_content"`
	Status      PostStatus  `json:"status"`
	NumRays     int32       `json:"num_rays"`
	NumComments int32       `json:"num_comments"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.PublisherID,
		arg.Title,
		arg.Subtitle,
		arg.Slug,
		arg.PostContent,
		arg.Status,
		arg.NumRays,
		arg.NumComments,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Subtitle,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
