// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPostsByUserToday = `-- name: CountPostsByUserToday :one
SELECT COUNT(*) FROM posts
WHERE publisher_id = $1 
AND created_at >= CURRENT_DATE
AND deleted_at IS NULL
`

func (q *Queries) CountPostsByUserToday(ctx context.Context, publisherID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByUserToday, publisherID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id,
    publisher_id,
    title,
    slug,
    post_content,
    num_rays,
    num_comments
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, publisher_id, title, slug, post_content, num_rays, num_comments, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	PostContent []byte      `json:"post_content"`
	NumRays     int32       `json:"num_rays"`
	NumComments int32       `json:"num_comments"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.PublisherID,
		arg.Title,
		arg.Slug,
		arg.PostContent,
		arg.NumRays,
		arg.NumComments,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT 
    p.id,
    p.title,
    p.slug,
    p.post_content,
    p.num_rays,
    p.num_comments,
    p.created_at,
    -- Join the Cover Image Data
    pi.image_url AS cover_image_url,
    pi.alt_text AS cover_image_alt,
    -- Join the Publisher Data
    pr.username AS publisher_username,
    pr.profile_image_url AS publisher_avatar
FROM posts p
LEFT JOIN post_images pi ON p.id = pi.post_id AND pi.is_cover_image = true
LEFT JOIN profiles pr ON p.publisher_id = pr.id
WHERE p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPostsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	PostContent       []byte             `json:"post_content"`
	NumRays           int32              `json:"num_rays"`
	NumComments       int32              `json:"num_comments"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CoverImageUrl     *string            `json:"cover_image_url"`
	CoverImageAlt     *string            `json:"cover_image_alt"`
	PublisherUsername *string            `json:"publisher_username"`
	PublisherAvatar   *string            `json:"publisher_avatar"`
}

// Grab the image ONLY if it is marked as the cover image
// Grab the publisher's profile
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PostContent,
			&i.NumRays,
			&i.NumComments,
			&i.CreatedAt,
			&i.CoverImageUrl,
			&i.CoverImageAlt,
			&i.PublisherUsername,
			&i.PublisherAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentlyDeletePost = `-- name: PermanentlyDeletePost :one
DELETE FROM posts
WHERE id = $1 AND publisher_id = $2
RETURNING id, publisher_id, title, slug, post_content, num_rays, num_comments, created_at, updated_at, deleted_at
`

type PermanentlyDeletePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
}

func (q *Queries) PermanentlyDeletePost(ctx context.Context, arg PermanentlyDeletePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, permanentlyDeletePost, arg.ID, arg.PublisherID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectPostByID = `-- name: SelectPostByID :one
SELECT id, publisher_id, title, slug, post_content, num_rays, num_comments, created_at, updated_at, deleted_at FROM posts
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) SelectPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, selectPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectPostBySlug = `-- name: SelectPostBySlug :one
SELECT id, publisher_id, title, slug, post_content, num_rays, num_comments, created_at, updated_at, deleted_at FROM posts
WHERE slug = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) SelectPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, selectPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePost = `-- name: SoftDeletePost :one
UPDATE posts
SET
    deleted_at = NOW()
WHERE id = $1 AND publisher_id = $2
RETURNING id, publisher_id, title, slug, post_content, num_rays, num_comments, created_at, updated_at, deleted_at
`

type SoftDeletePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, softDeletePost, arg.ID, arg.PublisherID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET 
    title = $3,
    slug = $4,
    post_content = $5,
    num_rays = $6,
    num_comments = $7,
    updated_at = NOW()
WHERE id = $1 AND publisher_id = $2 AND deleted_at IS NULL -- do we need to include publisher id to limit only publishers to update?
RETURNING id, publisher_id, title, slug, post_content, num_rays, num_comments, created_at, updated_at, deleted_at
`

type UpdatePostParams struct {
	ID          pgtype.UUID `json:"id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	PostContent []byte      `json:"post_content"`
	NumRays     int32       `json:"num_rays"`
	NumComments int32       `json:"num_comments"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.PublisherID,
		arg.Title,
		arg.Slug,
		arg.PostContent,
		arg.NumRays,
		arg.NumComments,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Title,
		&i.Slug,
		&i.PostContent,
		&i.NumRays,
		&i.NumComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
