// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_videos.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPostVideo = `-- name: CreatePostVideo :one
INSERT INTO post_videos (
    post_id,
    youtube_video_id,
    video_metadata
) VALUES (
    $1, $2, $3
)
RETURNING id, post_id, youtube_video_id, video_metadata, created_at
`

type CreatePostVideoParams struct {
	PostID         pgtype.UUID `json:"post_id"`
	YoutubeVideoID string      `json:"youtube_video_id"`
	VideoMetadata  []byte      `json:"video_metadata"`
}

func (q *Queries) CreatePostVideo(ctx context.Context, arg CreatePostVideoParams) (PostVideo, error) {
	row := q.db.QueryRow(ctx, createPostVideo,
		arg.PostID,
		arg.YoutubeVideoID,
		arg.VideoMetadata,
	)
	var i PostVideo
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
		&i.CreatedAt,
	)
	return i, err
}

const deletePostVideo = `-- name: DeletePostVideo :one
DELETE FROM post_videos
WHERE post_videos.id = $1 AND post_id = $2
AND EXISTS (
    SELECT 1 FROM posts 
    WHERE posts.id = $2 AND posts.publisher_id = $3
)
RETURNING id, post_id, youtube_video_id, video_metadata, created_at
`

type DeletePostVideoParams struct {
	ID          pgtype.UUID `json:"id"`
	PostID      pgtype.UUID `json:"post_id"`
	PublisherID pgtype.UUID `json:"publisher_id"`
}

func (q *Queries) DeletePostVideo(ctx context.Context, arg DeletePostVideoParams) (PostVideo, error) {
	row := q.db.QueryRow(ctx, deletePostVideo, arg.ID, arg.PostID, arg.PublisherID)
	var i PostVideo
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
		&i.CreatedAt,
	)
	return i, err
}

const listVideoFeed = `-- name: ListVideoFeed :many
SELECT
    pv.id AS video_id,
    pv.youtube_video_id,
    pv.video_metadata,
    p.id AS post_id,
    p.title AS post_title,
    p.slug AS post_slug,
    p.publisher_id,
    p.num_rays,
    p.num_comments,
    pv.created_at
FROM post_videos pv
INNER JOIN posts p ON pv.post_id = p.id
WHERE p.deleted_at IS NULL
ORDER BY pv.created_at DESC
LIMIT $1 OFFSET $2
`

type ListVideoFeedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListVideoFeedRow struct {
	VideoID        pgtype.UUID        `json:"video_id"`
	YoutubeVideoID string             `json:"youtube_video_id"`
	VideoMetadata  []byte             `json:"video_metadata"`
	PostID         pgtype.UUID        `json:"post_id"`
	PostTitle      string             `json:"post_title"`
	PostSlug       string             `json:"post_slug"`
	PublisherID    pgtype.UUID        `json:"publisher_id"`
	NumRays        int32              `json:"num_rays"`
	NumComments    int32              `json:"num_comments"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListVideoFeed(ctx context.Context, arg ListVideoFeedParams) ([]ListVideoFeedRow, error) {
	rows, err := q.db.Query(ctx, listVideoFeed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideoFeedRow
	for rows.Next() {
		var i ListVideoFeedRow
		if err := rows.Scan(
			&i.VideoID,
			&i.YoutubeVideoID,
			&i.VideoMetadata,
			&i.PostID,
			&i.PostTitle,
			&i.PostSlug,
			&i.PublisherID,
			&i.NumRays,
			&i.NumComments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPostVideoByID = `-- name: SelectPostVideoByID :one
SELECT id, post_id, youtube_video_id, video_metadata, created_at FROM post_videos
WHERE id = $1 LIMIT 1
`

func (q *Queries) SelectPostVideoByID(ctx context.Context, id pgtype.UUID) (PostVideo, error) {
	row := q.db.QueryRow(ctx, selectPostVideoByID, id)
	var i PostVideo
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
		&i.CreatedAt,
	)
	return i, err
}

const selectPostVideoByPostID = `-- name: SelectPostVideoByPostID :one
SELECT id, post_id, youtube_video_id, video_metadata, created_at FROM post_videos
WHERE post_id = $1 LIMIT 1
`

func (q *Queries) SelectPostVideoByPostID(ctx context.Context, postID pgtype.UUID) (PostVideo, error) {
	row := q.db.QueryRow(ctx, selectPostVideoByPostID, postID)
	var i PostVideo
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
		&i.CreatedAt,
	)
	return i, err
}

const updatePostVideo = `-- name: UpdatePostVideo :one
UPDATE post_videos 
SET
    youtube_video_id = $3,
    video_metadata = $4
WHERE post_videos.id = $1 AND post_id = $2
AND EXISTS (
    SELECT 1 FROM posts
    WHERE posts.id = $2 AND posts.publisher_id = $5
)
RETURNING id, post_id, youtube_video_id, video_metadata, created_at
`

type UpdatePostVideoParams struct {
	ID             pgtype.UUID `json:"id"`
	PostID         pgtype.UUID `json:"post_id"`
	YoutubeVideoID string      `json:"youtube_video_id"`
	VideoMetadata  []byte      `json:"video_metadata"`
	PublisherID    pgtype.UUID `json:"publisher_id"`
}

func (q *Queries) UpdatePostVideo(ctx context.Context, arg UpdatePostVideoParams) (PostVideo, error) {
	row := q.db.QueryRow(ctx, updatePostVideo,
		arg.ID,
		arg.PostID,
		arg.YoutubeVideoID,
		arg.VideoMetadata,
		arg.PublisherID,
	)
	var i PostVideo
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.YoutubeVideoID,
		&i.VideoMetadata,
		&i.CreatedAt,
	)
	return i, err
}
