// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_images.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPostImage = `-- name: CreatePostImage :one
INSERT INTO post_images (
    id,
    post_id,
    image_url,
    image_description,
    alt_text,
    is_cover_image
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, post_id, image_url, image_description, alt_text, is_cover_image, created_at
`

type CreatePostImageParams struct {
	ID               pgtype.UUID `json:"id"`
	PostID           pgtype.UUID `json:"post_id"`
	ImageUrl         string      `json:"image_url"`
	ImageDescription *string     `json:"image_description"`
	AltText          *string     `json:"alt_text"`
	IsCoverImage     bool        `json:"is_cover_image"`
}

func (q *Queries) CreatePostImage(ctx context.Context, arg CreatePostImageParams) (PostImage, error) {
	row := q.db.QueryRow(ctx, createPostImage,
		arg.ID,
		arg.PostID,
		arg.ImageUrl,
		arg.ImageDescription,
		arg.AltText,
		arg.IsCoverImage,
	)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ImageUrl,
		&i.ImageDescription,
		&i.AltText,
		&i.IsCoverImage,
		&i.CreatedAt,
	)
	return i, err
}

const deletePostImage = `-- name: DeletePostImage :one
DELETE FROM post_images
WHERE id = $1 AND post_id = $2
RETURNING id, post_id, image_url, image_description, alt_text, is_cover_image, created_at
`

type DeletePostImageParams struct {
	ID     pgtype.UUID `json:"id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) DeletePostImage(ctx context.Context, arg DeletePostImageParams) (PostImage, error) {
	row := q.db.QueryRow(ctx, deletePostImage, arg.ID, arg.PostID)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ImageUrl,
		&i.ImageDescription,
		&i.AltText,
		&i.IsCoverImage,
		&i.CreatedAt,
	)
	return i, err
}

const selectPostImageByID = `-- name: SelectPostImageByID :one
SELECT id, post_id, image_url, image_description, alt_text, is_cover_image, created_at FROM post_images
WHERE id = $1 LIMIT 1
`

func (q *Queries) SelectPostImageByID(ctx context.Context, id pgtype.UUID) (PostImage, error) {
	row := q.db.QueryRow(ctx, selectPostImageByID, id)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ImageUrl,
		&i.ImageDescription,
		&i.AltText,
		&i.IsCoverImage,
		&i.CreatedAt,
	)
	return i, err
}

const selectPostImagesByPost = `-- name: SelectPostImagesByPost :many
SELECT id, post_id, image_url, image_description, alt_text, is_cover_image, created_at FROM post_images
WHERE post_id = $1
`

func (q *Queries) SelectPostImagesByPost(ctx context.Context, postID pgtype.UUID) ([]PostImage, error) {
	rows, err := q.db.Query(ctx, selectPostImagesByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostImage
	for rows.Next() {
		var i PostImage
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ImageUrl,
			&i.ImageDescription,
			&i.AltText,
			&i.IsCoverImage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostImage = `-- name: UpdatePostImage :one
UPDATE post_images
SET
    image_url = $3,
    image_description = $4,
    alt_text = $5,
    is_cover_image = $6
WHERE id = $1 AND post_id = $2
RETURNING id, post_id, image_url, image_description, alt_text, is_cover_image, created_at
`

type UpdatePostImageParams struct {
	ID               pgtype.UUID `json:"id"`
	PostID           pgtype.UUID `json:"post_id"`
	ImageUrl         string      `json:"image_url"`
	ImageDescription *string     `json:"image_description"`
	AltText          *string     `json:"alt_text"`
	IsCoverImage     bool        `json:"is_cover_image"`
}

func (q *Queries) UpdatePostImage(ctx context.Context, arg UpdatePostImageParams) (PostImage, error) {
	row := q.db.QueryRow(ctx, updatePostImage,
		arg.ID,
		arg.PostID,
		arg.ImageUrl,
		arg.ImageDescription,
		arg.AltText,
		arg.IsCoverImage,
	)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ImageUrl,
		&i.ImageDescription,
		&i.AltText,
		&i.IsCoverImage,
		&i.CreatedAt,
	)
	return i, err
}
