// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM profiles WHERE username = $1
)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    id, 
    first_name, 
    last_name, 
    username, 
    role,
    profile_image_url, 
    profile_bio
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at
`

type CreateProfileParams struct {
	ID              pgtype.UUID `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Username        string      `json:"username"`
	Role            string      `json:"role"`
	ProfileImageUrl *string     `json:"profile_image_url"`
	ProfileBio      []byte      `json:"profile_bio"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Role,
		arg.ProfileImageUrl,
		arg.ProfileBio,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.ProfileImageUrl,
		&i.ProfileBio,
		&i.NumRaysReceived,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at FROM profiles
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.ProfileImageUrl,
		&i.ProfileBio,
		&i.NumRaysReceived,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at FROM profiles
WHERE username = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.ProfileImageUrl,
		&i.ProfileBio,
		&i.NumRaysReceived,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at FROM profiles
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.ProfileImageUrl,
			&i.ProfileBio,
			&i.NumRaysReceived,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentlyDeleteProfile = `-- name: PermanentlyDeleteProfile :one
DELETE FROM profiles
WHERE id = $1
RETURNING id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at
`

func (q *Queries) PermanentlyDeleteProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, permanentlyDeleteProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.ProfileImageUrl,
		&i.ProfileBio,
		&i.NumRaysReceived,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectProfilePhoto = `-- name: SelectProfilePhoto :one
SELECT profile_image_url FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) SelectProfilePhoto(ctx context.Context, id pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, selectProfilePhoto, id)
	var profile_image_url *string
	err := row.Scan(&profile_image_url)
	return profile_image_url, err
}

const softDeleteProfile = `-- name: SoftDeleteProfile :one
UPDATE profiles
SET
    deleted_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, softDeleteProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.ProfileImageUrl,
		&i.ProfileBio,
		&i.NumRaysReceived,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    first_name = $2,
    last_name = $3,
    username = $4,
    role = $5,
    profile_image_url = $6,
    profile_bio = $7,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, first_name, last_name, username, profile_image_url, profile_bio, num_rays_received, role, created_at, updated_at, deleted_at
`

type UpdateProfileParams struct {
	ID              pgtype.UUID `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	Username        string      `json:"username"`
	Role            string      `json:"role"`
	ProfileImageUrl *string     `json:"profile_image_url"`
	ProfileBio      []byte      `json:"profile_bio"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Role,
		arg.ProfileImageUrl,
		arg.ProfileBio,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.ProfileImageUrl,
		&i.ProfileBio,
		&i.NumRaysReceived,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
