// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_posts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfPostIsSaved = `-- name: CheckIfPostIsSaved :one
SELECT EXISTS(
    SELECT 1 FROM saved_posts
    WHERE user_id = $1 AND post_id = $2
)
`

type CheckIfPostIsSavedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) CheckIfPostIsSaved(ctx context.Context, arg CheckIfPostIsSavedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfPostIsSaved, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSavedPostsForUser = `-- name: ListSavedPostsForUser :many
SELECT p.id, p.publisher_id, p.title, p.slug, p.post_content, p.num_rays, p.num_comments, p.created_at, p.updated_at, p.deleted_at 
FROM posts p
INNER JOIN saved_posts sp ON p.id = sp.post_id
WHERE sp.user_id = $1 AND p.deleted_at IS NULL
ORDER BY sp.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSavedPostsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListSavedPostsForUser(ctx context.Context, arg ListSavedPostsForUserParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listSavedPostsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.PublisherID,
			&i.Title,
			&i.Slug,
			&i.PostContent,
			&i.NumRays,
			&i.NumComments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePost = `-- name: SavePost :exec
INSERT INTO saved_posts (user_id, post_id)
VALUES ($1, $2)
`

type SavePostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) SavePost(ctx context.Context, arg SavePostParams) error {
	_, err := q.db.Exec(ctx, savePost, arg.UserID, arg.PostID)
	return err
}

const unsavePost = `-- name: UnsavePost :exec
DELETE FROM saved_posts
WHERE user_id = $1 AND post_id = $2
`

type UnsavePostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) UnsavePost(ctx context.Context, arg UnsavePostParams) error {
	_, err := q.db.Exec(ctx, unsavePost, arg.UserID, arg.PostID)
	return err
}
