// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchPosts = `-- name: SearchPosts :many
SELECT
    p.id,
    p.title,
    p.subtitle,
    p.slug,
    p.created_at,
    pr.username AS publisher_username,
    pr.profile_image_url AS publisher_avatar
FROM posts p
LEFT JOIN profiles pr ON p.publisher_id = pr.id
WHERE p.deleted_at IS NULL AND p.status = 'published'
AND to_tsvector('english', p.title || ' ' || COALESCE(p.subtitle, '')) @@ websearch_to_tsquery('english', $1)
ORDER BY ts_rank(to_tsvector('english', p.title || ' ' || COALESCE(p.subtitle, '')), websearch_to_tsquery('english', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchPostsParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
	Offset             int32  `json:"offset"`
}

type SearchPostsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Subtitle          *string            `json:"subtitle"`
	Slug              string             `json:"slug"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PublisherUsername *string            `json:"publisher_username"`
	PublisherAvatar   *string            `json:"publisher_avatar"`
}

// Combine Title and Subtitle into one and search
// sort by relevance rank (how well matched)
func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.WebsearchToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Slug,
			&i.CreatedAt,
			&i.PublisherUsername,
			&i.PublisherAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProfiles = `-- name: SearchProfiles :many
SELECT
    id,
    username,
    first_name,
    last_name,
    profile_image_url,
    subscriber_tier
FROM profiles 
WHERE deleted_at IS NULL
AND (
    username ILIKE '%' || $1::text || '%'
    OR first_name ILIKE '%' || $1::text || '%'
    OR last_name ILIKE '%' || $1::text || '%'
)

ORDER BY
    (username ILIKE $1::text || '%') DESC,
    (first_name ILIKE $1::text || '%') DESC,
    num_rays_received DESC
LIMIT $2 OFFSET $3
`

type SearchProfilesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchProfilesRow struct {
	ID              pgtype.UUID    `json:"id"`
	Username        string         `json:"username"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	ProfileImageUrl *string        `json:"profile_image_url"`
	SubscriberTier  SubscriberTier `json:"subscriber_tier"`
}

func (q *Queries) SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]SearchProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchProfiles, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProfilesRow
	for rows.Next() {
		var i SearchProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.ProfileImageUrl,
			&i.SubscriberTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
